### ISSUE TITLE
-d command does not work with ensembl GTF file

### ISSUE THREAD

**Issue by gtvall** [RacconC/gtftools#2]
Hello,
I am attempting to used the -d function with this program but it continues to output  the following:
IndexError: list index out of range

I am using the most recent ensembl gtf and other functions work with my gtf file. I am wondering if perhaps the -d function is incompatible with ensembl gtf files?

**Comment by hjjansen** [comment]
I'm not sure if you still need an answer but I ran int the same problem. So I leave what I've done here so it could be useful for anybody running into this error.
My traceback looked like this:
```Traceback (most recent call last):
  File "/trinity/shared/apps/miniforge3/envs/gtftools/bin/gtftools", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/trinity/shared/apps/miniforge3/envs/gtftools/lib/python3.13/site-packages/gtftools/gtftools.py", line 1016, in main
    get_independent_intron(GTFfile,independent_intron_file=args.independent_intron,chroms=chroms)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/trinity/shared/apps/miniforge3/envs/gtftools/lib/python3.13/site-packages/gtftools/gtftools.py", line 492, in get_independent_intron
    genebed=get_gene_bed(GTFfile,chroms=chroms)
  File "/trinity/shared/apps/miniforge3/envs/gtftools/lib/python3.13/site-packages/gtftools/gtftools.py", line 267, in get_gene_bed
    symbol = line.split('gene_name')[1].split('"')[1].upper()
             ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
I asked chatGPT and the answer I got was:

> The error you're encountering indicates that there is an issue with the code trying to split a line of data and access the `"gene_name"` value in a GTF (General Feature Format) file. Specifically, it's running into an `IndexError` because it expects to find a `"gene_name"` field, but it's not able to do so.
> 
> Here’s a breakdown of the key parts of the error:
> 
> The error occurs in `gtftools.py` at line 267 where the code tries to extract the gene name from a line in the GTF file.
> 
> `line.split('gene_name')[1]` tries to split the line by the string `'gene_name'`, and then access the part after it (using `[1]`).
> The error means that the split operation is not returning what the code expects, which suggests that the `"gene_name"` key may be missing or formatted differently in the GTF file.
> The `IndexError: list index out of range` means the split didn’t produce a second part (i.e., after gene_name, there was no valid data to access).
> 
> ### **Possible Causes:**
> The GTF file might have entries that do not contain `"gene_name"`, or the `"gene_name"` attribute may be formatted differently or missing.
> The GTF format might not be consistent throughout the file (e.g., missing or differently formatted attributes for certain lines).
> The script might expect a specific GTF format version or structure that doesn't match the one you're using.
> ### **Steps to Troubleshoot and Resolve:**
> **Inspect the GTF file**: Open the GTF file and look for lines where `"gene_name"` is missing or improperly formatted. This can help identify where the problem occurs.
> 
> Check if the `"gene_name"` attribute exists in all lines, especially in the lines that are being processed at the time of the error.
> Make sure that the format follows standard GTF conventions for gene annotations.
> **Add a safety check**: You can modify the script (if possible) to add a check before splitting the line to ensure `"gene_name"` exists.
> 
> For example, instead of:
> 
> `symbol = line.split('gene_name')[1].split('"')[1].upper()`
> You could check if `'gene_name'` exists in the line before trying to split:
> 
> ```
> if 'gene_name' in line:
>     symbol = line.split('gene_name')[1].split('"')[1].upper()
> else:
>     # Handle missing gene_name (skip or assign a default value)
>     symbol = 'Unknown'  # or handle as needed
> ```
> **Check GTF file format**: Ensure the GTF file follows the expected format. You can validate it using tools like `gtf-validator` or `gffread` to check for formatting errors.
> 
> **Check for Empty Lines**: Sometimes empty lines or lines that don't conform to the expected GTF structure can cause parsing errors. Make sure the file doesn't have empty lines or malformed entries.
> 
> **Verify Script Version**: Make sure that the version of `gtftools` you're using is compatible with your GTF file. If the tool expects a specific version of the GTF format, consider converting your file to the correct version or using a different tool that handles the format properly.

I repaired my gtf file by adding the `gene_name` attribute. For some genes there was a `gene` attribute with a name which I changed into `gene_name`. For the other genes which didn't have the `gene` attribute I inserted `gene_name "Unknown";`
That solved this isue for me.
